import { PortalApiError, type CreateSigningSessionRequest, type DocumentDetail, type DocumentListFilters, type DocumentsApi, type SigningSession } from '@adaptivecash/api-client';
import { documentFixtures } from './fixtures';
export interface MockDocumentsController { api:DocumentsApi; failNextList():void; setListLatency(search:string,ms:number):void; loseNextCreateResponse():void; commands:CreateSigningSessionRequest[]; }
const clone=<T,>(v:T):T=>structuredClone(v);
const wait=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve,reject)=>{const id=setTimeout(resolve,ms); signal?.addEventListener('abort',()=>{clearTimeout(id); reject(new DOMException('Aborted','AbortError'));},{once:true});});
export function createMockDocumentsApi():MockDocumentsController { let fail=false,lose=false,seq=0; const latency=new Map<string,number>(); const sessions=new Map<string,SigningSession>(); const keys=new Map<string,string>(); const commands:CreateSigningSessionRequest[]=[]; const api:DocumentsApi={
 async listDocuments(tenant,filters:DocumentListFilters,signal){await wait(latency.get(filters.search??'')??20,signal); if(fail){fail=false;throw new PortalApiError(503,{title:'Unavailable',status:503});} return documentFixtures.filter(x=>x.id.startsWith(tenant==='branch-demo'?'BR-':'CU-')).filter(x=>!filters.status||x.status===filters.status).filter(x=>!filters.search||x.title.toLowerCase().includes(filters.search.toLowerCase())).map(({signingSession,...x})=>clone(x));},
 async getDocument(tenant,id,signal){await wait(20,signal); const doc=documentFixtures.find(x=>x.id===id&&x.id.startsWith(tenant==='branch-demo'?'BR-':'CU-')); if(!doc)throw new PortalApiError(404,{title:'Not found',status:404}); return clone(doc);},
 async getActiveSigningSession(_tenant,id){return clone([...sessions.values()].find(x=>x.documentId===id&&!['Verified','Failed','Expired'].includes(x.status))??null);},
 async createSigningSession(_tenant,request,signal){commands.push(clone(request));await wait(20,signal); const existing=keys.get(request.idempotencyKey); if(existing)return clone(sessions.get(existing)!); const session:SigningSession={id:`SIGN-${++seq}`,documentId:request.documentId,status:'Pending',provider:'Fake Qualified Provider',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+300000).toISOString()}; sessions.set(session.id,session);keys.set(request.idempotencyKey,session.id);if(lose){lose=false;throw new PortalApiError(504,{title:'Response lost after acceptance',status:504,code:'RESPONSE_LOST'});}return clone(session);},
 async getSigningSession(_tenant,id,signal){await wait(20,signal);const s=sessions.get(id);if(!s)throw new PortalApiError(404,{title:'Not found',status:404});return clone(s);}
 }; return {api,commands,failNextList(){fail=true},setListLatency(q,ms){latency.set(q,ms)},loseNextCreateResponse(){lose=true}}; }
